spring.application.name=ProLinkBE

spring.datasource.url=jdbc:sqlserver://mssqlstud.fhict.local:1433;databaseName=dbi547091_s1s;encrypt=true;trustServerCertificate=true
spring.datasource.username=dbi547091_s1s
spring.datasource.password=secret
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

